# Generated by Django 3.0.5 on 2020-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0001_auto_20200425_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='auction',
            name='place',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='base_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='auctionhouse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lot',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='images',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lot',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lot',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
