# Generated by Django 3.0.5 on 2020-04-26 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0002_auto_20200425_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot',
            name='job',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='search_all',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
